export const FETCH_RANDOM_QUOTE = 'FETCH_RANDOM_QUOTE';
export const FETCH_RANDOM_QUOTE_SUCCESS = 'FETCH_RANDOM_QUOTE_SUCCESS';
export const ADD_TO_PREVIOUS_QUOTES = 'ADD_TO_PREVIOUS_QUOTES';
export const FETCH_IP_SUCCESS = 'FETCH_IP_SUCCESS';
